name: Publish Docker (shinsenter/php)

################################################################################
################################################################################

on:
  schedule:
    - cron: "0 0 * * 2"
  push:
    branches:
      - main

################################################################################
################################################################################

jobs:
  ##############################################################################
  ##############################################################################

  base_image:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        base:
          - ubuntu
        version:
          - "20.04"
          - focal
          - latest
    env:
      DOCKER_BUILDKIT: "1"
      OS_BASE: ${{ matrix.base }}
      OS_VERSION: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Restore cache layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Create cache path
        run: |
          mkdir -p /tmp/.buildx
          docker buildx create --use
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          tags: shinsenter/s6-ubuntu:${{ matrix.version }}
          context: "{{defaultContext}}:src/base/"
          cache-from: type=local,src=/tmp/.buildx
          cache-to: type=local,dest=/tmp/.buildx-new,mode=max
          push: true
          pull: true
      - name: Swap cache path
        run: |
          rm -rf /tmp/.buildx
          mv /tmp/.buildx-new /tmp/.buildx

  ##############################################################################
  ##############################################################################

  php_images:
    needs: base_image
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        php_variation:
          - cli
          - fpm
          - fpm-apache
          - fpm-nginx
        php_version:
          - "7.4"
          - "8.0"
          - "8.1"
    env:
      PHP_VERSION: ${{ matrix.php_version }}
      IMAGE_BASE: shinsenter/s6-ubuntu:latest
      IMAGE_NAME: shinsenter/php
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Restore cache layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Create cache path
        run: |
          mkdir -p /tmp/.buildx
          docker buildx create --use
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          tags: shinsenter/php:${{ matrix.php_version }}-${{ matrix.php_variation }}
          context: "{{defaultContext}}:src/php/${{ matrix.php_variation }}/"
          cache-from: type=local,src=/tmp/.buildx
          cache-to: type=local,dest=/tmp/.buildx-new,mode=max
          push: true
          pull: true
      - name: Swap cache path
        run: |
          rm -rf /tmp/.buildx
          mv /tmp/.buildx-new /tmp/.buildx

################################################################################
################################################################################
