# This file belongs to the project https://code.shin.company/php
# Author:  Shin <shin@shin.company>
# License: https://code.shin.company/php/blob/main/LICENSE
################################################################################

name: Update Changelog (deprecated)

################################################################################
################################################################################

on: workflow_dispatch

################################################################################
################################################################################

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      - uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
          compare-url-target-revision: ${{ github.event.release.target_commitish }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: 'Update CHANGELOG.md for ${{ github.event.release.tag_name }}'
          file_pattern: CHANGELOG.md

################################################################################
################################################################################
